#!/bin/bash
# Train and evaluate UMS on the four wildfire/smoke datasets.
# Usage: bash run.sh [GPU_ID] [SEED]
#
# Prerequisites:
#   1. Place preprocessed datasets under data/{DATASET}/data_{train,val,test}.pkl
#   2. Place tile embedding files (tile_embeddings_*.pt) in this directory
#      (generated by extract_embeddings/extract_tile_embeddings_*.py)
#   3. Install dependencies: pip install -r requirements.txt
#      Also requires DSTPP: https://github.com/DSTPP/DSTPP

GPU=${1:-0}
SEED=${2:-42}

EMB_EMAS="tile_embeddings_eMAS_z7_flat.pt"
EMB_GK2A="tile_embeddings_GK2A_z7_flat.pt"
EMB_GOES18="tile_embeddings_GOES18_z7_flat.pt"

run_dataset() {
    local DS=$1 ZOOM=$2 EMB=$3
    echo "=== Training on ${DS} (seed=${SEED}) ==="
    CUDA_VISIBLE_DEVICES=${GPU} python train.py \
        --dataset ${DS} \
        --zoom ${ZOOM} \
        --emb_file ${EMB} \
        --total_epochs 500 \
        --seed ${SEED} \
        --alpha_knn 0.005 \
        --cuda_id 0

    echo "=== Evaluating ${DS} ==="
    CUDA_VISIBLE_DEVICES=${GPU} python test.py \
        --dataset ${DS} \
        --zoom ${ZOOM} \
        --emb_file ${EMB} \
        --model_ckpt models_mm/${DS}_seed${SEED}/model_best.pkl \
        --cuda_id 0 \
        --n_samples 3
}

run_dataset eMAS        7 ${EMB_EMAS}
run_dataset GK2A_fire   7 ${EMB_GK2A}
run_dataset eMAS_smoke  7 ${EMB_EMAS}
run_dataset GOES18_smoke 7 ${EMB_GOES18}
